name: dartrix
description: An Extensible Template Engine for Dart. Comes with a set of builtin templates, and supports extension by "plugin" template libraries.
# homepage:
repository: https://github.com/mobileink/dartrix
version: 0.1.4-alpha

dependencies:
  ansicolor: ^1.0.2
  args: ^1.5.3
  glob: ^1.2.0
  logging: ^0.11.4
  mustache_template: ^1.0.0+1
  package_config: ^1.9.2
  # package_resolver: ^1.0.10
  path: ^1.6.4
  process_run: ^0.10.7
  pubspec_yaml: ^1.0.0+1
  # pub_cache: ^0.2.3
  # resource: ^2.1.6
  sprintf: ^4.0.2
  strings: ^0.1.2

dev_dependencies:

environment:
  sdk: '>=2.6.0 <3.0.0'

executables:
  dxlist: list
  dxman: man
  dxnew: new
  dxsanity: sanity
  dxupdate: update

